import { BasicColumn } from '/@/components/Table/src/types/table';
import { getBookkeepingTemplateAPI } from '/@/api/finance/finance';
import { FilterIcon, CustomRender, FilterDropdown } from '/@/views/common/CustomTable/index';

const tableSetting = {
  title: '凭证模板',
  titleHelpMessage: '自动制证',
  api: getBookkeepingTemplateAPI,
};

const SearchDropdown = FilterDropdown.useSearchDropdown(getBookkeepingTemplateAPI);

const columns: BasicColumn[] = [
  {
    title: '模板编码',
    dataIndex: 'code',
    width: 150,
    sorter: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '模板名称',
    dataIndex: 'name',
    width: 250,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '公司代码',
    dataIndex: 'companyCode',
    width: 100,
    filters: [],
    filterIcon: FilterIcon.FilterIcon,
    customRender: CustomRender.Text,
  },
  {
    title: '凭证类型',
    dataIndex: 'type',
    width: 100,
    filters: [],
    filterIcon: FilterIcon.FilterIcon,
    customRender: CustomRender.Text,
  },
  {
    title: '摘要',
    dataIndex: 'abstract',
    width: 300,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '借方科目代码',
    dataIndex: ['debitFinanceAccount', 'code'],
    width: 150,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '借方科目名称',
    dataIndex: ['debitFinanceAccount', 'name'],
    width: 300,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '借方辅助帐类型',
    dataIndex: ['debitFinanceAccount', 'auxiliaryGroup', 'name'],
    width: 250,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '借方金额',
    dataIndex: 'debitAmount',
    width: 150,
    customRender: CustomRender.Text,
  },
  {
    title: '贷方科目代码',
    dataIndex: ['creditFinanceAccount', 'code'],
    width: 150,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '贷方科目名称',
    dataIndex: ['creditFinanceAccount', 'name'],
    width: 300,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '贷方辅助帐类型',
    dataIndex: ['creditFinanceAccount', 'auxiliaryGroup', 'name'],
    width: 250,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '贷方金额',
    dataIndex: 'creditAmount',
    width: 150,
    customRender: CustomRender.Text,
  },
  {
    title: '是否有现金流量',
    dataIndex: 'isCashflow',
    width: 150,
    filters: [],
    filterIcon: FilterIcon.FilterIcon,
    customRender: CustomRender.Text,
  },
  {
    title: '现金流量标记',
    dataIndex: 'cashflowTag',
    width: 150,
    filters: [],
    filterIcon: FilterIcon.FilterIcon,
    customRender: CustomRender.Text,
  },
  {
    title: '制单人',
    dataIndex: 'lister',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '审核人',
    dataIndex: 'auditor',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '过账人',
    dataIndex: 'confirmor',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '记账日期',
    dataIndex: 'bookkeepingDate',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '业务日期',
    dataIndex: 'businessDate',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '会计期间',
    dataIndex: 'period',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '凭证号',
    dataIndex: 'voucherId',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '分录号',
    dataIndex: 'entryNo',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '币种',
    dataIndex: 'currencyType',
    width: 150,
    defaultHidden: true,
    filters: [],
    filterIcon: FilterIcon.FilterIcon,
    customRender: CustomRender.Text,
  },
  {
    title: '汇率',
    dataIndex: 'currencyRate',
    width: 150,
    defaultHidden: true,
    customRender: CustomRender.Text,
  },
  {
    title: '方向',
    dataIndex: 'direction',
    width: 150,
    defaultHidden: true,
    filters: [],
    filterIcon: FilterIcon.FilterIcon,
    customRender: CustomRender.Text,
  },
  {
    title: '原币金额',
    dataIndex: 'currencyAmount',
    width: 150,
    defaultHidden: true,
    customRender: CustomRender.Text,
  },
  {
    title: '数量',
    dataIndex: 'count',
    width: 150,
    defaultHidden: true,
    customRender: CustomRender.Text,
  },
  {
    title: '单价',
    dataIndex: 'unitPrice',
    width: 150,
    defaultHidden: true,
    customRender: CustomRender.Text,
  },
  {
    title: '附件数量',
    dataIndex: 'attachCount',
    width: 150,
    defaultHidden: true,
    customRender: CustomRender.Text,
  },
  {
    title: '过账标记',
    dataIndex: 'isConfirm',
    width: 150,
    defaultHidden: true,
    filters: [],
    filterIcon: FilterIcon.FilterIcon,
    customRender: CustomRender.Text,
  },
  {
    title: '机制凭证模块',
    dataIndex: 'machineModule',
    width: 150,
    defaultHidden: true,
    customRender: CustomRender.Text,
  },
  {
    title: '删除标记',
    dataIndex: 'isDeleted',
    width: 150,
    defaultHidden: true,
    customRender: CustomRender.Text,
  },
  {
    title: '凭证序号',
    dataIndex: 'voucherNo',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '单位',
    dataIndex: 'unit',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '参考信息',
    dataIndex: 'referenceInformation',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '业务编号',
    dataIndex: 'businessNo',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '结算方式',
    dataIndex: 'payment',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '结算号',
    dataIndex: 'payNo',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
  {
    title: '到期日',
    dataIndex: 'dueDate',
    width: 150,
    defaultHidden: true,
    filterIcon: FilterIcon.SearchIcon,
    filterDropdown: SearchDropdown,
    customRender: CustomRender.Text,
  },
];

export const tableConfig = {
  ...tableSetting,
  columns,
};
