import { BasicColumn } from '/@/components/Table/src/types/table';
import { getBookkeepingTemplateAPI } from '/@/api/sys/finance';

const tableSetting = {
  title: '凭证模板',
  titleHelpMessage: '自动制证',
  api: getBookkeepingTemplateAPI,
};

const basicColumns: BasicColumn[] = [
  {
    title: '模板编码',
    dataIndex: 'code',
    width: 150,
    slots: { filterIcon: 'searchIcon', filterDropdown: 'searchDropdown', customRender: 'Text' },
  },
  {
    title: '模板名称',
    dataIndex: 'name',
    width: 250,
    slots: { filterIcon: 'searchIcon', filterDropdown: 'searchDropdown', customRender: 'Text' },
  },
  {
    title: '公司代码',
    dataIndex: 'companyCode',
    width: 100,
    filters: [],
    slots: { filterIcon: 'filterIcon', customRender: 'Text' },
  },
  {
    title: '凭证类型',
    dataIndex: 'type',
    width: 100,
    filters: [],
    slots: { filterIcon: 'filterIcon', customRender: 'Text' },
  },
  {
    title: '摘要',
    dataIndex: 'abstract',
    width: 300,
    slots: { filterIcon: 'searchIcon', filterDropdown: 'searchDropdown', customRender: 'Text' },
  },
  {
    title: '借方科目代码',
    dataIndex: 'debitFinanceAccount.code',
    width: 150,
    slots: { filterIcon: 'searchIcon', filterDropdown: 'searchDropdown', customRender: 'Text' },
  },
  {
    title: '借方科目名称',
    dataIndex: 'debitFinanceAccount.name',
    width: 300,
    slots: { filterIcon: 'searchIcon', filterDropdown: 'searchDropdown', customRender: 'Text' },
  },
  {
    title: '借方辅助帐类型',
    dataIndex: 'debitFinanceAccount.auxiliaryGroup.name',
    width: 250,
    slots: { filterIcon: 'searchIcon', filterDropdown: 'searchDropdown', customRender: 'Text' },
  },
  {
    title: '借方金额',
    dataIndex: 'debitAmount',
    width: 150,
  },
  {
    title: '贷方科目代码',
    dataIndex: 'creditFinanceAccount.code',
    width: 150,
    slots: { filterIcon: 'searchIcon', filterDropdown: 'searchDropdown', customRender: 'Text' },
  },
  {
    title: '贷方科目名称',
    dataIndex: 'creditFinanceAccount.name',
    width: 300,
    slots: { filterIcon: 'searchIcon', filterDropdown: 'searchDropdown', customRender: 'Text' },
  },
  {
    title: '贷方辅助帐类型',
    dataIndex: 'creditFinanceAccount.auxiliaryGroup.name',
    width: 250,
    slots: { filterIcon: 'searchIcon', filterDropdown: 'searchDropdown', customRender: 'Text' },
  },
  {
    title: '贷方金额',
    dataIndex: 'creditAmount',
    width: 150,
  },
  {
    title: '是否有现金流量',
    dataIndex: 'isCashflow',
    width: 150,
    filters: [],
    slots: { filterIcon: 'filterIcon', customRender: 'Text' },
  },
  {
    title: '现金流量标记',
    dataIndex: 'cashflowTag',
    width: 150,
  },
  {
    title: '制单人',
    dataIndex: 'lister',
    width: 150,
    defaultHidden: true,
    slots: { customRender: 'Text' },
  },
  {
    title: '审核人',
    dataIndex: 'auditor',
    width: 150,
    defaultHidden: true,
    slots: { customRender: 'Text' },
  },
  {
    title: '过账人',
    dataIndex: 'confirmor',
    width: 150,
    defaultHidden: true,
    slots: { customRender: 'Text' },
  },
  {
    title: '记账日期',
    dataIndex: 'bookkeepingDate',
    width: 150,
    defaultHidden: true,
    slots: { customRender: 'Text' },
  },
  {
    title: '业务日期',
    dataIndex: 'businessDate',
    width: 150,
    defaultHidden: true,
    slots: { customRender: 'Text' },
  },
  {
    title: '会计期间',
    dataIndex: 'period',
    width: 150,
    defaultHidden: true,
    slots: { customRender: 'Text' },
  },
  {
    title: '凭证号',
    dataIndex: 'voucherId',
    width: 150,
    defaultHidden: true,
    slots: { customRender: 'Text' },
  },
  {
    title: '分录号',
    dataIndex: 'entryNo',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '币种',
    dataIndex: 'currencyType',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '汇率',
    dataIndex: 'currencyRate',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '方向',
    dataIndex: 'direction',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '原币金额',
    dataIndex: 'currencyAmount',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '数量',
    dataIndex: 'count',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '单价',
    dataIndex: 'unitPrice',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '附件数量',
    dataIndex: 'attachCount',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '过账标记',
    dataIndex: 'isConfirm',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '机制凭证模块',
    dataIndex: 'machineModule',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '删除标记',
    dataIndex: 'isDeleted',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '凭证序号',
    dataIndex: 'voucherNo',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '单位',
    dataIndex: 'unit',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '参考信息',
    dataIndex: 'referenceInformation',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '业务编号',
    dataIndex: 'businessNo',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '结算方式',
    dataIndex: 'payment',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '结算号',
    dataIndex: 'payNo',
    width: 150,
    defaultHidden: true,
  },
  {
    title: '到期日',
    dataIndex: 'dueDate',
    width: 150,
    defaultHidden: true,
  },
];

export const tableData = {
  tableSetting,
  basicColumns,
};
